name: Publish
on:
  release:
    types: [released]

env:
  NPM_TOKEN: ""

jobs:
  publish-canary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Setup Node Environment
        uses: actions/setup-node@v4
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        uses: Borales/actions-yarn@v4
        with:
          cmd: install
      - name: Build
        uses: Borales/actions-yarn@v4
        with:
          cmd: build
      - name: Test
        uses: Borales/actions-yarn@v4
        with:
          cmd: git-hook-tasks pre-push
      - name: Publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}
          TAG_NAME: ${{ github.event.release.tag_name }}
        run: |-
          npm version --no-git-tag-version "$TAG_NAME" ?> /dev/null | true && npm publish
